#!/usr/bin/python3
# shebang
import sys
jjpFile = sys.argv[1]

try:
    program = open(jjpFile).read()
except Exception:
    raise Exception('Houve um problema para encontrar ou ler o programa.')

Lines = program.split('\n')
