#!/usr/bin/python3
# shebang
import sys
import json
from src.controllers.LexicaController import LexicaController
jjpFile = sys.argv[1]


try:
    program = open(jjpFile).read()
    confWords = json.load(open('./src/config/configWords.json'))
    
except Exception:
    raise Exception('Houve um problema para encontrar ou ler o programa.')

Lines = program.split('\n')
